### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by fededido** [hopandfork/hopandfork.github.io#5] opened 2016-11-15 15:40 UTC
The site still uses the old favicon, it should be updated to match the new logo.

**Comment by grussorusso** [comment] 2016-11-15 20:48
Fixed by #80f281b. You may still see the old favicon, but now the issue is simply related to caching. If you browse the website using a different browser, you will correctly see the new logo.

**Closed as completed by grussorusso** 2016-11-15 20:48 UTC
Labels: bug
